name: cross-embodiment
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.0
      - cloudpickle==3.1.1
      - decorator==5.2.1
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filelock==3.19.1
      - fsspec==2025.9.0
      - glfw==2.10.0
      - grpcio==1.75.1
      - gym==0.26.2
      - gym-notices==0.1.0
      - h5py==3.14.0
      - importlib-resources==6.5.2
      - ipdb==0.13.13
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - llvmlite==0.45.0
      - markdown==3.9
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - mujoco==2.3.6
      - networkx==3.4.2
      - numba==0.62.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pynput==1.8.1
      - pyopengl==3.1.10
      - python-xlib==0.33
      - pyyaml==6.0.3
      - robosuite==1.4.0
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - scipy==1.15.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - tomli==2.2.1
      - torch==2.8.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-extensions==4.15.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - zipp==3.23.0
prefix: /home/ubuntu/miniconda3/envs/ma
